////
// //
// PippinSoft
//
//

package pippin.pui;


import java.util.*;


/**
* A PEvent is an event generated by a PComponent.
* PEvents occur on a PAppliance and are transmitted
* to all interested listeners via the PUI layer event handling
* methods.
*/
public class PEvent extends EventObject {

	public PEvent(PComponent source) {
		super(source);
	}

	/**
	* @return
	* The PComponent that is the source of this PEvent.
	*/
	public PComponent getComponent() {
		return (PComponent) getSource();
	}
}
