/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jadi_echo_EchoWrapper */

#ifndef _Included_com_jadi_echo_EchoWrapper
#define _Included_com_jadi_echo_EchoWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jadi_echo_EchoWrapper
 * Method:    analyzeEcho
 * Signature: ([D[II)V
 */
JNIEXPORT void JNICALL Java_com_jadi_echo_EchoWrapper_analyzeEcho
  (JNIEnv *, jclass, jdoubleArray, jintArray, jint);

 
#define DllExport extern "C" _declspec ( dllexport ) BOOL _stdcall 

_declspec(dllexport) BOOL doAnalyze(double* output, int* input, int level);

HINSTANCE loadEchoDLL(LPCSTR library);

void releaseEchoDLL(HINSTANCE hDLL);


#ifdef __cplusplus



}
#endif
#endif
