/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EchoWrapper */

#ifndef _Included_EchoWrapper
#define _Included_EchoWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EchoWrapper
 * Method:    analyzeEcho
 * Signature: ([D[II)V
 */
JNIEXPORT void JNICALL Java_EchoWrapper_analyzeEcho
  (JNIEnv *, jclass, jdoubleArray, jintArray, jint);

/*
 * Class:     EchoWrapper
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EchoWrapper_test
  (JNIEnv *, jclass);

BOOL doAnalyze(double* output, int* input, int* level);

HINSTANCE loadEchoDLL(LPCSTR library);

void releaseEchoDLL(HINSTANCE hDLL);
#ifdef __cplusplus
}
#endif
#endif
