/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class telesync_qov_EchoWrapper */

#ifndef _Included_telesync_qov_EchoWrapper
#define _Included_telesync_qov_EchoWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     telesync_qov_EchoWrapper
 * Method:    analyzeEcho
 * Signature: ([D[II)V
 */
JNIEXPORT void JNICALL Java_telesync_qov_EchoWrapper_analyzeEcho
  (JNIEnv *, jclass, jdoubleArray, jintArray, jint);

/*
 * Class:     telesync_qov_EchoWrapper
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_telesync_qov_EchoWrapper_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
