select  COUNT(*) from LOAD_PLNG_PLT WHERE PLND_LOAD_EFF_DT = trunc(current_date)

select  COUNT(*) from STG_LOAD_PLNG_PLT_H
WHERE CRT_TS >= {ts '2018-01-12 02:18:00'} AND CRT_TS < {ts '2018-01-12 02:24:00'} and PLND_LOAD_EFF_DT = trunc(current_date)

SELECT A.SCHN_EFS_RTE_ID, B.SCHN_EFS_RTE_ID FROM
  (
    SELECT SCHN_EFS_RTE_ID
    FROM plnd_load_grp_h
    WHERE HIST_CRT_TS >= {ts '2018-01-12 10:00:00'} AND HIST_CRT_TS < {ts '2018-01-12 10:15:00'} AND
          PLND_LOAD_EFF_DT = trunc(current_date)
  ) A LEFT JOIN PLND_LOAD_GRP B ON A.SCHN_EFS_RTE_ID = B.SCHN_EFS_RTE_ID, SCHN_EFS_RTE_STP S, SCHN_EFS_RTE_STP S3, SCHN_EFS_RTE_STP_XREF X,
    OGVNDR_EFF_RTE_SCH O, MBMVNDR_LOC_OPARM PARM
WHERE B.SCHN_EFS_RTE_ID IS NULL
AND A.SCHN_EFS_RTE_ID = S.SCHN_EFS_RTE_ID
AND S.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT N NULL
AND X.BKUP_SCHN_EFS_RTE_STP_ID = S3.SCHN_EFS_RTE_STP_ID
AND S3.SCHN_EFS_RTE_STP_ID = O.SCHN_EFS_RTE_STP_ID
AND O.MBAS_MVNDR_NBR = PARM.MBAS_MVNDR_NBR
AND O.DEST_SCHN_LOC_ID = PARM.DEST_SCHN_LOC_ID
AND PARM.SCHN_ONBRD_PARM_CD = 2
AND PARM.PARM_DT_VAL <= trunc(current_date)



SELECT *
    FROM plnd_load_grp_h
    WHERE HIST_CRT_TS >= {ts '2018-01-12 10:00:00'} AND HIST_CRT_TS < {ts '2018-01-12 10:15:00'} AND
          PLND_LOAD_EFF_DT = trunc(current_date) AND SCHN_EFS_RTE_ID = 13815

select * from plnd_load_h where plnd_load_grp_id = 426403

select * from plnd_load_sku_h where plnd_load_id = 932325


select * from STG_LOAD_PLNG_PLT where schn_ord_grp_id in
                                      (select s.schn_ord_grp_id from schN_efs_rte_stp s, schn_efs_rte_stp_xref x, schn_efs_rte_stp s1
                                      where s.schn_efs_rte_stp_id = x.BKUP_SCHN_EFS_RTE_STP_ID and x.PRI_SCHN_EFS_RTE_STP_ID = s1.SCHN_EFS_RTE_STP_ID
                                      and s1.schN_efs_rte_id = 13815)

  SELECT
					  A.MBAS_MVNDR_NBR AS MBAS_MVNDR_NBR,
					  A.MBAS_DEPT_NBR AS MBAS_DEPT_NBR,
					  A.MBAS_SKU_NBR AS MBAS_SKU_NBR,
					  A.DCM_FCST_CPNT_TYP_CD AS DCM_FCST_CPNT_TYP_CD,
					  A.MER_BASE_CD AS MER_BASE_CD,
					  A.ORIG_SCHN_LOC_ID,
					  A.DEST_SCHN_LOC_ID,
					  A.STR_SCHN_LOC_ID,
					  B.SRC_LOC_ID AS ORIG_SCHN_LOC,
					  C.SRC_LOC_ID AS DEST_SCHN_LOC,
					  D.SRC_LOC_ID AS STR_SCHN_LOC
					  FROM
					  LOAD_PLNG_STR_DMND A
					  INNER JOIN SCHN_CNSL_LOC_XREF B
					  ON A.ORIG_SCHN_LOC_ID = B.SCHN_LOC_ID
					  AND B.SCHN_CNSL_LOC_SRC_SYS_CD = 1
					  INNER JOIN SCHN_CNSL_LOC_XREF C
					  ON A.DEST_SCHN_LOC_ID = C.SCHN_LOC_ID
					  AND C.SCHN_CNSL_LOC_SRC_SYS_CD = 2
					  INNER JOIN SCHN_CNSL_LOC_XREF D
					  ON A.STR_SCHN_LOC_ID = D.SCHN_LOC_ID
					  AND D.SCHN_CNSL_LOC_SRC_SYS_CD = 2
					  WHERE 1=1 AND A.MBAS_MVNDR_NBR = 640105
            AND A.MBAS_DEPT_NBR = 28
            AND A.MBAS_SKU_NBR = 1002810581
            AND A.MER_BASE_CD = 1
            AND B.SRC_LOC_ID = '640506TX001'
            AND C.SRC_LOC_ID = '5023';

640105
28
5023
1002810581

select * from schn_cnsl_loc_xref where src_loc_id = '640506TX001'

select * from schn_cnsl_loc_xref where src_loc_id = '5023'

select * from SCHN_ORD_GRP_LANE where ORIG_SCHN_LOC_ID = 789 and DEST_SCHN_LOC_ID = 287

select * from MBMVNDR_LOC_OPARM where DEST_SCHN_LOC_ID = 287 and MBAS_MVNDR_NBR = 640105 and SCHN_ONBRD_PARM_CD = 2

select * from plnd_load_grp_h where schn_efs_rte_id = 1789 and hist_crt_ts >= {ts '2018-01-09 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-10 04:00:00'}

select * from schn_ord_grp where SCHN_ORD_GRP_LANE_ID = 1281

select * from schn_efs_rte_stp where SCHN_ORD_GRP_ID = 1281

select * from plnd_load_h where PLND_LOAD_GRP_ID = 424699

select * from plnd_ltl_load_h where plnd_load_grp_id = 424699

select * from plnd_load_sku_h where plnd_load_id in (928880,928881) and MBAS_SKU_NBR = 1002810581

select * from plnd_ltl_load_sku_h where LTL_LOAD_ID = 451633 and mbas_sku_nbr = 1002810581

select * from load_plng_fcst_dly_h where mbas_sku_nbr = 1002810581
and MBAS_SHP_TO_LOC_NBR = 5023
and ORIG_TMS_FAC_ALIAS_ID = '640506TX001'
and hist_crt_ts >= {ts '2018-01-09 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-10 04:00:00'}

select * from schn_efs_rte_stats where schN_efs_rte_id = 1789

select distinct mbas_mvndr_nbr from load_plng_fcst_dly where mbas_sku_nbr = 1002810581

select * from load_plng_fcst_dly_h where mbas_sku_nbr = 1002810581
and MBAS_SHP_TO_LOC_NBR = 5023
and ORIG_TMS_FAC_ALIAS_ID = '640506TX001'
and hist_crt_ts >= {ts '2018-01-08 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-09 04:00:00'}
and DCM_FCST_CPNT_TYP_CD in (1,2,3)

select * from load_plng_fcst_dly_h where LOAD_PLNG_DLY_FCST_ID in (668582866)

SELECT DISTINCT R.SCHN_EFS_RTE_ID IFC_RTE, S.SCHN_ORD_GRP_ID OG3, OL.SRC_LOC_ID ORIGIN, DL.SRC_LOC_ID DEST
	--, OL.SCHN_LOC_ID, DL.SCHN_LOC_ID
	, V.MBAS_MVNDR_NBR, V.MBAS_DEPT_NBR, V.SCHN_ORD_GRP_VNDR_ID
	, OO.PARM_DT_VAL ONBOARD_DT, NVL(PARM.PARM_FLG_VAL, 'N') RND_UP_FLG
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V LEFT JOIN SCHN_ORD_GRP_VNDR_PARM PARM ON (V.SCHN_ORD_GRP_VNDR_ID = PARM.SCHN_ORD_GRP_VNDR_ID AND PARM.LOAD_PLNG_PARM_CD = 1),
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
--AND R.SCHN_EFS_RTE_ID = 9898
--AND OO.PARM_DT_VAL <= CURRENT_DATE

SELECT COUNT(DISTINCT SCHN_ORD_GRP_ID) FROM STG_LOAD_PLNG_PLT

SELECT COUNT(*) FROM LOAD_PLNG_PLT WHERE CRT_TS <= {ts '2018-01-15 23:47:13'}

select AVG(ACT_PLT_UTILZTN_VOL_PCT) from STG_LOAD_PLNG_PLT

select AVG(ACT_PLT_UTILZTN_VOL_PCT) from STG_LOAD_PLNG_PLT_H
WHERE HIST_CRT_TS>= {ts '2018-01-17 08:00:00'}

select * from LOAD_PLNG_EXTNL_DMND where byo_nbr = 12 and po_ctrl_nbr = 75565

select * from LOAD_PLNG_EXTNL_DMND_LOC where LOAD_PLNG_EXTNL_DMND_ID = 2104

select B.SRC_LOC_ID from LOAD_PLNG_EXTNL_DMND_LOC A, SCHN_CNSL_LOC_XREF B where ACT_ORD_OPEN_DT = trunc(current_date)
and STR_SCHN_LOC_ID = B.SCHN_LOC_ID and B.SCHN_CNSL_LOC_SRC_SYS_CD = 2

select * from PRE_PLND_LOAD_HRQST_X order by last_upd_ts desc --where LAST_UPD_TS = trunc(current_date)

select distinct LOAD_PLNG_EXTNL_DMND_LOC_ID from PPLSKU_LPLNG_EDMND_X where pre_pln_load_id = 10585949

select * from LOAD_PLNG_FCST_DLY where mbas_mvndr_nbr = 383625 and MBAS_SHP_TO_LOC_NBR = 5085 and MBAS_SKU_NBR = 208124

select * from load_plng_err where mbas_mvndr_nbr = '383625' and MBAS_SHP_TO_LOC_NBR = '5085' and MBAS_SKU_NBR = 208124

select * from mvndr_sku_dc where mvndr_nbr = 383625 and sku_nbr = 208124 and dc_nbr = 5085

SELECT PARM.SCHN_ORD_GRP_VNDR_ID
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V LEFT JOIN SCHN_ORD_GRP_VNDR_PARM PARM ON (V.SCHN_ORD_GRP_VNDR_ID = PARM.SCHN_ORD_GRP_VNDR_ID AND PARM.LOAD_PLNG_PARM_CD = 1),
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
--AND OO.PARM_DT_VAL <= CURRENT_DATE

select * from MBMVNDR_LOC_OPARM where mbas_mvndr_nbr = 19149 and MBAS_SHTO_LOC_NBR = 641

select * from N_SCHN_ONBRD_PARM where SCHN_ONBRD_PARM_CD = 11

SELECT * FROM LOAD_PLNG_FCST_DLY WHERE MBAS_MVNDR_NBR = 19149

select * from load_plng_err where mbas_mvndr_nbr = 19149 and ORIG_TMS_FAC_ALIAS_ID = '31792PA101' and MBAS_ORIG_LOC_NBR = 5089 order by crt_ts desc

select * from OGVNDR_EFF_RTE_SCH where DEST_SCHN_LOC_ID = 641 and MBAS_MVNDR_NBR = 19149

select * from schn_cnsl_loc_xref where schn_loc_id = 641

select * from mvndr_sku_dc where mvndr_nbr = 19149 and dc_nbr = 5089

select * from plnd_load_sku_h where hist_crt_ts >= {ts '2018-01-15 23:00:00'} and HIST_CRT_TS <=


select * from N_LOAD_PLNG_PARM where LOAD_PLNG_PARM_CD = 19

select * from schn_efs_rte_stp_xref where PRI_SCHN_EFS_RTE_STP_ID = 17402

select * from schn_efs_rte_stp where SCHN_EFS_RTE_STP_ID = 17402

select * from SCHN_EFS_SCH_DT_V where schn_efs_Rte_id= 16723

select * from LPLNG_PARM_CTGRY_XREF where LOAD_PLNG_PARM_CD= 8

select * from N_LOAD_PLNG_PARM_CTGRY

select * from schn_appl_evnt_log where SCHN_TRANS_WRKFLW_NBR = 5686 and crt_ts >= {ts '2018-01-25 18:00:00'}
																			 --
SELECT
					DISTINCT  B.SCHN_EFS_RTE_STP_ID,
					C.SCHN_ORD_GRP_ID,
					E.LOAD_PLNG_PARM_CD,
					PARM_CHAR_VAL,
					PARM_INTG_VAL,
					PARM_DEC_VAL,
					PARM_FLG_VAL,
					F.LOAD_PLNG_PARM_TYP_IND,
					G.LOAD_PLNG_PARM_CTGRY_CD,
					E.EFF_BGN_DT,
					E.EFF_END_DT
					FROM SCHN_EFS_RTE A,
					SCHN_EFS_RTE_STP B,
					SCHN_ORD_GRP C,
					SCHN_ORD_GRP_VNDR D,
					SCHN_ORD_GRP_VNDR_PARM E,
					LOAD_PLNG_PARM_CD F,
					LPLNG_PARM_CTGRY_XREF G
					WHERE A.SCHN_EFS_RTE_ID = 8546
					AND (A.EFF_BGN_DT <= {ts '2018-02-19'} AND A.EFF_END_DT >= current_date)
					AND A.ACTV_FLG = 'Y'
					AND A.SCHN_EFS_RTE_ID = B.SCHN_EFS_RTE_ID
					AND (B.EFF_BGN_DT <= {ts '2018-02-19'} AND B.EFF_END_DT >= current_date )
					AND A.ACTV_FLG = B.ACTV_FLG
					AND B.SCHN_ORD_GRP_ID = C.SCHN_ORD_GRP_ID
					AND G.LOAD_PLNG_PARM_CTGRY_CD = 2
					AND (C.EFF_BGN_DT <= {ts '2018-02-19'} AND C.EFF_END_DT >= current_date )
					AND C.ACTV_FLG = 'Y'
					AND C.SCHN_ORD_GRP_ID = D.SCHN_ORD_GRP_ID
					AND C.ACTV_FLG = D.ACTV_FLG
					AND (D.EFF_BGN_DT <= {ts '2018-02-19'} AND D.EFF_END_DT >= current_date )
					AND D.SCHN_ORD_GRP_VNDR_ID = E.SCHN_ORD_GRP_VNDR_ID
					AND C.ACTV_FLG = E.ACTV_FLG
					AND (E.EFF_BGN_DT <= {ts '2018-02-19'} AND E.EFF_END_DT >= current_date )
					AND E.LOAD_PLNG_PARM_CD = F.LOAD_PLNG_PARM_CD
					AND E.LOAD_PLNG_PARM_CD = G.LOAD_PLNG_PARM_CD ;


-- FIND IFC SKUs that did not make it onto a pallet
SELECT DISTINCT R.SCHN_EFS_RTE_ID IFC_RTE, S.SCHN_ORD_GRP_ID OG3, OL.SRC_LOC_ID ORIGIN, DL.SRC_LOC_ID DEST
	--, OL.SCHN_LOC_ID, DL.SCHN_LOC_ID
	, V.MBAS_MVNDR_NBR, V.MBAS_DEPT_NBR, V.SCHN_ORD_GRP_VNDR_ID
	, OO.PARM_DT_VAL ONBOARD_DT, F.MBAS_SKU_NBR
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V,
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL,
	LOAD_PLNG_FCST_DLY F
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
AND OO.PARM_DT_VAL <= trunc(current_date)
AND OL.SRC_LOC_ID = F.ORIG_TMS_FAC_ALIAS_ID
AND DL.SRC_LOC_ID = F.MBAS_SHP_TO_LOC_NBR
AND V.MBAS_MVNDR_NBR = F.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = F.MBAS_DEPT_NBR
AND V.MER_BASE_CD = F.MER_BASE_CD
AND F.DCM_FCST_CPNT_TYP_CD IN (1,2)
AND F.DAY_5_VAL != 0
AND NOT EXISTS (
		SELECT PLS.MBAS_SKU_NBR FROM
			PLND_LOAD_GRP PG,
			PLND_LOAD_GRP_VER PGV,
			PLND_LOAD PL,
			PLND_LOAD_SKU PLS,
			PLSKU_LPLNG_PLT_X PX
		WHERE
			PG.SCHN_EFS_RTE_ID = R.SCHN_EFS_RTE_ID
			AND PG.PLND_LOAD_GRP_ID = PGV.PLND_LOAD_GRP_ID
			AND PL.PLND_LOAD_ID = PL.PLND_LOAD_ID
			AND PGV.PLND_LOAD_GRP_ORD_ELIG_FLG = 'Y'
			AND PGV.PLND_LOAD_GRP_VER_NBR = PL.PLND_LOAD_GRP_VER_NBR
			AND PL.PLND_LOAD_ID = PLS.PLND_LOAD_ID
			AND PLS.MBAS_SKU_NBR = F.MBAS_SKU_NBR
			AND PLS.MBAS_MVNDR_NBR = F.MBAS_MVNDR_NBR
			AND PLS.PLND_LOAD_ID = PX.PLND_LOAD_ID
			AND PLS.MBAS_SKU_NBR = PX.MBAS_SKU_NBR)
select  COUNT(*) from STG_LOAD_PLNG_PLT_H
WHERE CRT_TS >= {ts '2018-01-12 02:18:00'} AND CRT_TS < {ts '2018-01-12 02:24:00'} and PLND_LOAD_EFF_DT = trunc(current_date)

SELECT A.SCHN_EFS_RTE_ID, B.SCHN_EFS_RTE_ID FROM
  (
    SELECT SCHN_EFS_RTE_ID
    FROM plnd_load_grp_h
    WHERE HIST_CRT_TS >= {ts '2018-01-12 10:00:00'} AND HIST_CRT_TS < {ts '2018-01-12 10:15:00'} AND
          PLND_LOAD_EFF_DT = trunc(current_date)
  ) A LEFT JOIN PLND_LOAD_GRP B ON A.SCHN_EFS_RTE_ID = B.SCHN_EFS_RTE_ID, SCHN_EFS_RTE_STP S, SCHN_EFS_RTE_STP S3, SCHN_EFS_RTE_STP_XREF X,
    OGVNDR_EFF_RTE_SCH O, MBMVNDR_LOC_OPARM PARM
WHERE B.SCHN_EFS_RTE_ID IS NULL
AND A.SCHN_EFS_RTE_ID = S.SCHN_EFS_RTE_ID
AND S.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT N NULL
AND X.BKUP_SCHN_EFS_RTE_STP_ID = S3.SCHN_EFS_RTE_STP_ID
AND S3.SCHN_EFS_RTE_STP_ID = O.SCHN_EFS_RTE_STP_ID
AND O.MBAS_MVNDR_NBR = PARM.MBAS_MVNDR_NBR
AND O.DEST_SCHN_LOC_ID = PARM.DEST_SCHN_LOC_ID
AND PARM.SCHN_ONBRD_PARM_CD = 2
AND PARM.PARM_DT_VAL <= trunc(current_date)



SELECT *
    FROM plnd_load_grp_h
    WHERE HIST_CRT_TS >= {ts '2018-01-12 10:00:00'} AND HIST_CRT_TS < {ts '2018-01-12 10:15:00'} AND
          PLND_LOAD_EFF_DT = trunc(current_date) AND SCHN_EFS_RTE_ID = 13815

select * from plnd_load_h where plnd_load_grp_id = 426403

select * from plnd_load_sku_h where plnd_load_id = 932325


select * from STG_LOAD_PLNG_PLT where schn_ord_grp_id in
                                      (select s.schn_ord_grp_id from schN_efs_rte_stp s, schn_efs_rte_stp_xref x, schn_efs_rte_stp s1
                                      where s.schn_efs_rte_stp_id = x.BKUP_SCHN_EFS_RTE_STP_ID and x.PRI_SCHN_EFS_RTE_STP_ID = s1.SCHN_EFS_RTE_STP_ID
                                      and s1.schN_efs_rte_id = 13815)

  SELECT
					  A.MBAS_MVNDR_NBR AS MBAS_MVNDR_NBR, 
					  A.MBAS_DEPT_NBR AS MBAS_DEPT_NBR, 
					  A.MBAS_SKU_NBR AS MBAS_SKU_NBR,  
					  A.DCM_FCST_CPNT_TYP_CD AS DCM_FCST_CPNT_TYP_CD, 
					  A.MER_BASE_CD AS MER_BASE_CD,  
					  A.ORIG_SCHN_LOC_ID, 
					  A.DEST_SCHN_LOC_ID, 
					  A.STR_SCHN_LOC_ID, 
					  B.SRC_LOC_ID AS ORIG_SCHN_LOC, 
					  C.SRC_LOC_ID AS DEST_SCHN_LOC, 
					  D.SRC_LOC_ID AS STR_SCHN_LOC 
					  FROM 
					  LOAD_PLNG_STR_DMND A 
					  INNER JOIN SCHN_CNSL_LOC_XREF B
					  ON A.ORIG_SCHN_LOC_ID = B.SCHN_LOC_ID 
					  AND B.SCHN_CNSL_LOC_SRC_SYS_CD = 1
					  INNER JOIN SCHN_CNSL_LOC_XREF C
					  ON A.DEST_SCHN_LOC_ID = C.SCHN_LOC_ID 
					  AND C.SCHN_CNSL_LOC_SRC_SYS_CD = 2
					  INNER JOIN SCHN_CNSL_LOC_XREF D
					  ON A.STR_SCHN_LOC_ID = D.SCHN_LOC_ID 
					  AND D.SCHN_CNSL_LOC_SRC_SYS_CD = 2
					  WHERE 1=1 AND A.MBAS_MVNDR_NBR = 640105
            AND A.MBAS_DEPT_NBR = 28
            AND A.MBAS_SKU_NBR = 1002810581
            AND A.MER_BASE_CD = 1
            AND B.SRC_LOC_ID = '640506TX001'
            AND C.SRC_LOC_ID = '5023';

640105
28
5023
1002810581

select * from schn_cnsl_loc_xref where src_loc_id = '640506TX001'

select * from schn_cnsl_loc_xref where src_loc_id = '5023'

select * from SCHN_ORD_GRP_LANE where ORIG_SCHN_LOC_ID = 789 and DEST_SCHN_LOC_ID = 287

select * from MBMVNDR_LOC_OPARM where DEST_SCHN_LOC_ID = 287 and MBAS_MVNDR_NBR = 640105 and SCHN_ONBRD_PARM_CD = 2

select * from plnd_load_grp_h where schn_efs_rte_id = 1789 and hist_crt_ts >= {ts '2018-01-09 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-10 04:00:00'}

select * from schn_ord_grp where SCHN_ORD_GRP_LANE_ID = 1281

select * from schn_efs_rte_stp where SCHN_ORD_GRP_ID = 1281

select * from plnd_load_h where PLND_LOAD_GRP_ID = 424699

select * from plnd_ltl_load_h where plnd_load_grp_id = 424699

select * from plnd_load_sku_h where plnd_load_id in (928880,928881) and MBAS_SKU_NBR = 1002810581

select * from plnd_ltl_load_sku_h where LTL_LOAD_ID = 451633 and mbas_sku_nbr = 1002810581

select * from load_plng_fcst_dly_h where mbas_sku_nbr = 1002810581
and MBAS_SHP_TO_LOC_NBR = 5023
and ORIG_TMS_FAC_ALIAS_ID = '640506TX001'
and hist_crt_ts >= {ts '2018-01-09 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-10 04:00:00'}

select * from schn_efs_rte_stats where schN_efs_rte_id = 1789

select distinct mbas_mvndr_nbr from load_plng_fcst_dly where mbas_sku_nbr = 1002810581

select * from load_plng_fcst_dly_h where mbas_sku_nbr = 1002810581
and MBAS_SHP_TO_LOC_NBR = 5023
and ORIG_TMS_FAC_ALIAS_ID = '640506TX001'
and hist_crt_ts >= {ts '2018-01-08 23:00:00'}
and HIST_CRT_TS < {ts '2018-01-09 04:00:00'}
and DCM_FCST_CPNT_TYP_CD in (1,2,3)

select * from load_plng_fcst_dly_h where LOAD_PLNG_DLY_FCST_ID in (668582866)

SELECT DISTINCT R.SCHN_EFS_RTE_ID IFC_RTE, S.SCHN_ORD_GRP_ID OG3, OL.SRC_LOC_ID ORIGIN, DL.SRC_LOC_ID DEST
	--, OL.SCHN_LOC_ID, DL.SCHN_LOC_ID
	, V.MBAS_MVNDR_NBR, V.MBAS_DEPT_NBR, V.SCHN_ORD_GRP_VNDR_ID
	, OO.PARM_DT_VAL ONBOARD_DT, NVL(PARM.PARM_FLG_VAL, 'N') RND_UP_FLG
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V LEFT JOIN SCHN_ORD_GRP_VNDR_PARM PARM ON (V.SCHN_ORD_GRP_VNDR_ID = PARM.SCHN_ORD_GRP_VNDR_ID AND PARM.LOAD_PLNG_PARM_CD = 1),
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
--AND R.SCHN_EFS_RTE_ID = 9898
--AND OO.PARM_DT_VAL <= CURRENT_DATE

SELECT COUNT(DISTINCT SCHN_ORD_GRP_ID) FROM STG_LOAD_PLNG_PLT

SELECT COUNT(*) FROM LOAD_PLNG_PLT WHERE CRT_TS <= {ts '2018-01-15 23:47:13'}

select AVG(ACT_PLT_UTILZTN_VOL_PCT) from STG_LOAD_PLNG_PLT

select AVG(ACT_PLT_UTILZTN_VOL_PCT) from STG_LOAD_PLNG_PLT_H
WHERE HIST_CRT_TS>= {ts '2018-01-17 08:00:00'}

select * from LOAD_PLNG_EXTNL_DMND where byo_nbr = 12 and po_ctrl_nbr = 75565

select * from LOAD_PLNG_EXTNL_DMND_LOC where LOAD_PLNG_EXTNL_DMND_ID = 2104

select B.SRC_LOC_ID from LOAD_PLNG_EXTNL_DMND_LOC A, SCHN_CNSL_LOC_XREF B where ACT_ORD_OPEN_DT = trunc(current_date)
and STR_SCHN_LOC_ID = B.SCHN_LOC_ID and B.SCHN_CNSL_LOC_SRC_SYS_CD = 2

select * from PRE_PLND_LOAD_HRQST_X order by last_upd_ts desc --where LAST_UPD_TS = trunc(current_date)

select distinct LOAD_PLNG_EXTNL_DMND_LOC_ID from PPLSKU_LPLNG_EDMND_X where pre_pln_load_id = 10585949

select * from LOAD_PLNG_FCST_DLY where mbas_mvndr_nbr = 383625 and MBAS_SHP_TO_LOC_NBR = 5085 and MBAS_SKU_NBR = 208124

select * from load_plng_err where mbas_mvndr_nbr = '383625' and MBAS_SHP_TO_LOC_NBR = '5085' and MBAS_SKU_NBR = 208124

select * from mvndr_sku_dc where mvndr_nbr = 383625 and sku_nbr = 208124 and dc_nbr = 5085

SELECT PARM.SCHN_ORD_GRP_VNDR_ID
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V LEFT JOIN SCHN_ORD_GRP_VNDR_PARM PARM ON (V.SCHN_ORD_GRP_VNDR_ID = PARM.SCHN_ORD_GRP_VNDR_ID AND PARM.LOAD_PLNG_PARM_CD = 1),
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
--AND OO.PARM_DT_VAL <= CURRENT_DATE

select * from MBMVNDR_LOC_OPARM where mbas_mvndr_nbr = 19149 and MBAS_SHTO_LOC_NBR = 641

select * from N_SCHN_ONBRD_PARM where SCHN_ONBRD_PARM_CD = 11

SELECT * FROM LOAD_PLNG_FCST_DLY WHERE MBAS_MVNDR_NBR = 19149

select * from load_plng_err where mbas_mvndr_nbr = 19149 and ORIG_TMS_FAC_ALIAS_ID = '31792PA101' and MBAS_ORIG_LOC_NBR = 5089 order by crt_ts desc

select * from OGVNDR_EFF_RTE_SCH where DEST_SCHN_LOC_ID = 641 and MBAS_MVNDR_NBR = 19149

select * from schn_cnsl_loc_xref where schn_loc_id = 641

select * from mvndr_sku_dc where mvndr_nbr = 19149 and dc_nbr = 5089

select * from plnd_load_sku_h where hist_crt_ts >= {ts '2018-01-15 23:00:00'} and HIST_CRT_TS <=


select * from N_LOAD_PLNG_PARM where LOAD_PLNG_PARM_CD = 19

select * from schn_efs_rte_stp_xref where PRI_SCHN_EFS_RTE_STP_ID = 17402

select * from schn_efs_rte_stp where SCHN_EFS_RTE_STP_ID = 17402

select * from SCHN_EFS_SCH_DT_V where schn_efs_Rte_id= 16723

select * from LPLNG_PARM_CTGRY_XREF where LOAD_PLNG_PARM_CD= 8

select * from N_LOAD_PLNG_PARM_CTGRY

select * from schn_appl_evnt_log where SCHN_TRANS_WRKFLW_NBR = 5686 and crt_ts >= {ts '2018-01-25 18:00:00'}
																			 --
SELECT
					DISTINCT  B.SCHN_EFS_RTE_STP_ID,
					C.SCHN_ORD_GRP_ID,
					E.LOAD_PLNG_PARM_CD,
					PARM_CHAR_VAL,
					PARM_INTG_VAL,
					PARM_DEC_VAL,
					PARM_FLG_VAL,
					F.LOAD_PLNG_PARM_TYP_IND,
					G.LOAD_PLNG_PARM_CTGRY_CD,
					E.EFF_BGN_DT,
					E.EFF_END_DT
					FROM SCHN_EFS_RTE A,
					SCHN_EFS_RTE_STP B,
					SCHN_ORD_GRP C,
					SCHN_ORD_GRP_VNDR D,
					SCHN_ORD_GRP_VNDR_PARM E,
					LOAD_PLNG_PARM_CD F,
					LPLNG_PARM_CTGRY_XREF G
					WHERE A.SCHN_EFS_RTE_ID = 8546
					AND (A.EFF_BGN_DT <= {ts '2018-02-19'} AND A.EFF_END_DT >= current_date)
					AND A.ACTV_FLG = 'Y'
					AND A.SCHN_EFS_RTE_ID = B.SCHN_EFS_RTE_ID
					AND (B.EFF_BGN_DT <= {ts '2018-02-19'} AND B.EFF_END_DT >= current_date )
					AND A.ACTV_FLG = B.ACTV_FLG
					AND B.SCHN_ORD_GRP_ID = C.SCHN_ORD_GRP_ID
					AND G.LOAD_PLNG_PARM_CTGRY_CD = 2
					AND (C.EFF_BGN_DT <= {ts '2018-02-19'} AND C.EFF_END_DT >= current_date )
					AND C.ACTV_FLG = 'Y'
					AND C.SCHN_ORD_GRP_ID = D.SCHN_ORD_GRP_ID
					AND C.ACTV_FLG = D.ACTV_FLG
					AND (D.EFF_BGN_DT <= {ts '2018-02-19'} AND D.EFF_END_DT >= current_date )
					AND D.SCHN_ORD_GRP_VNDR_ID = E.SCHN_ORD_GRP_VNDR_ID
					AND C.ACTV_FLG = E.ACTV_FLG
					AND (E.EFF_BGN_DT <= {ts '2018-02-19'} AND E.EFF_END_DT >= current_date )
					AND E.LOAD_PLNG_PARM_CD = F.LOAD_PLNG_PARM_CD
					AND E.LOAD_PLNG_PARM_CD = G.LOAD_PLNG_PARM_CD ;


-- FIND IFC SKUs that did not make it onto a pallet
SELECT DISTINCT R.SCHN_EFS_RTE_ID IFC_RTE, S.SCHN_ORD_GRP_ID OG3, OL.SRC_LOC_ID ORIGIN, DL.SRC_LOC_ID DEST
	--, OL.SCHN_LOC_ID, DL.SCHN_LOC_ID
	, V.MBAS_MVNDR_NBR, V.MBAS_DEPT_NBR, V.SCHN_ORD_GRP_VNDR_ID
	, OO.PARM_DT_VAL ONBOARD_DT, F.MBAS_SKU_NBR
FROM
	SCHN_EFS_RTE_STP R,
	SCHN_EFS_RTE_STP_XREF X,
	SCHN_EFS_RTE_STP S,
	SCHN_ORD_GRP OG,
	SCHN_ORD_GRP_LANE L,
	SCHN_ORD_GRP_VNDR V,
	MBMVNDR_LOC_OPARM O LEFT JOIN MBMVNDR_LOC_OPARM OO ON
				(O.MBAS_MVNDR_NBR = OO.MBAS_MVNDR_NBR AND O.DEST_SCHN_LOC_ID = OO.DEST_SCHN_LOC_ID AND OO.SCHN_ONBRD_PARM_CD = 2),
	SCHN_CNSL_LOC_XREF OL,
	SCHN_CNSL_LOC_XREF DL,
	LOAD_PLNG_FCST_DLY F
WHERE
	R.SCHN_EFS_RTE_STP_ID = X.PRI_SCHN_EFS_RTE_STP_ID
  AND X.BKUP_SCHN_EFS_RTE_STP_ID = S.SCHN_EFS_RTE_STP_ID
AND S.SCHN_ORD_GRP_ID = OG.SCHN_ORD_GRP_ID
AND OG.SCHN_ORD_GRP_LANE_ID = L.SCHN_ORD_GRP_LANE_ID
AND OG.SCHN_ORD_GRP_ID = V.SCHN_ORD_GRP_ID
AND V.MBAS_MVNDR_NBR = O.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = O.MBAS_DEPT_NBR
AND L.DEST_SCHN_LOC_ID = O.DEST_SCHN_LOC_ID
AND L.ORIG_SCHN_LOC_ID = OL.SCHN_LOC_ID
AND L.DEST_SCHN_LOC_ID = DL.SCHN_LOC_ID
AND OL.SCHN_CNSL_LOC_SRC_SYS_CD = 1
AND DL.SCHN_CNSL_LOC_SRC_SYS_CD = 2
AND O.SCHN_ONBRD_PARM_CD = 9
AND O.PARM_DT_VAL <= CURRENT_DATE
AND X.SCND_SCHN_EFS_RTE_STP_ID IS NOT NULL
AND R.EFF_BGN_DT <= CURRENT_DATE AND R.EFF_END_DT >= CURRENT_DATE
AND S.EFF_BGN_DT <= CURRENT_DATE AND S.EFF_END_DT >= CURRENT_DATE
AND OG.EFF_BGN_DT <= CURRENT_DATE AND OG.EFF_END_DT >= CURRENT_DATE
AND OO.PARM_DT_VAL <= trunc(current_date)
AND OL.SRC_LOC_ID = F.ORIG_TMS_FAC_ALIAS_ID
AND DL.SRC_LOC_ID = F.MBAS_SHP_TO_LOC_NBR
AND V.MBAS_MVNDR_NBR = F.MBAS_MVNDR_NBR
AND V.MBAS_DEPT_NBR = F.MBAS_DEPT_NBR
AND V.MER_BASE_CD = F.MER_BASE_CD
AND F.DCM_FCST_CPNT_TYP_CD IN (1,2)
AND F.DAY_5_VAL != 0
AND NOT EXISTS (
		SELECT PLS.MBAS_SKU_NBR FROM
			PLND_LOAD_GRP PG,
			PLND_LOAD_GRP_VER PGV,
			PLND_LOAD PL,
			PLND_LOAD_SKU PLS,
			PLSKU_LPLNG_PLT_X PX
		WHERE
			PG.SCHN_EFS_RTE_ID = R.SCHN_EFS_RTE_ID
			AND PG.PLND_LOAD_GRP_ID = PGV.PLND_LOAD_GRP_ID
			AND PL.PLND_LOAD_ID = PL.PLND_LOAD_ID
			AND PGV.PLND_LOAD_GRP_ORD_ELIG_FLG = 'Y'
			AND PGV.PLND_LOAD_GRP_VER_NBR = PL.PLND_LOAD_GRP_VER_NBR
			AND PL.PLND_LOAD_ID = PLS.PLND_LOAD_ID
			AND PLS.MBAS_SKU_NBR = F.MBAS_SKU_NBR
			AND PLS.MBAS_MVNDR_NBR = F.MBAS_MVNDR_NBR
			AND PLS.PLND_LOAD_ID = PX.PLND_LOAD_ID
			AND PLS.MBAS_SKU_NBR = PX.MBAS_SKU_NBR)