package com.iobeam.gateway.web.gwadmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.runtime.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import com.iobeam.gateway.router.*;
import com.iobeam.gateway.web.admin.*;
import com.iobeam.gateway.util.GatewayConfiguration;

public class admin_jsp extends HttpJspBase {

  public String getServletInfo() {
    return "";
}

  private static java.util.Vector _jspx_includes;

  static {
    _jspx_includes = new java.util.Vector(1);
    _jspx_includes.add("/gwadmin/includes/menu.html");
  }

  public java.util.List getIncludes() {
    return _jspx_includes;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    javax.servlet.jsp.PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n");

	GatewayConfiguration gconfig = GatewayConfiguration.getInstance();

	if (!AdminLogon.checkCredentials(request)) {
		response.sendRedirect("login.jsp");
	}

	String msg = (String)request.getAttribute("msg");
	if (msg == null) msg = "";

	SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss z");
	sdf.setTimeZone(
		TimeZone.getTimeZone(gconfig.getProperty("iobeam.gateway.timezone")));

	String localtime = sdf.format(new Date());


      out.write("\n\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/gwadmin/iobeam.css\"/>\n");
      out.write("<title>\n\tVenue ");
      out.print(gconfig.getProperty("iobeam.gateway.venue.id"));
      out.write("\n");
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("<body marginheight=0 leftmargin=0 topmargin=0 bgcolor=\"#FFFFFF\"\nbackground=\"/gwadmin/images/insideBkgd.jpg\">\n");
      out.write("<table border=0 cellspacing=0 cellpadding=0 width=\"760\">\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\" colspan=\"2\">");
      out.write("<img src=\"/gwadmin/images/inside_01.jpg\">\n\t");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"center\" width=\"180\" valign=\"top\">\n\t\t");
      out.write("<table border=0 cellpadding=0 cellspacing=2 width=\"70%\">\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("<a href=\"/gwadmin/admin.jsp\">\n\t\t");
      out.write("<font class=\"linkfont\">Settings");
      out.write("</font>");
      out.write("</a>\n\t");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("<a href=\"/admincontrol?type=leases\">");
      out.write("<font class=\"linkfont\">\n\t\tActive Leases");
      out.write("</font>");
      out.write("</a>\n\t");
      out.write("</td>\n");
      out.write("</tr>\n\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("<a href=\"/admincontrol?type=tasks\">");
      out.write("<font class=\"linkfont\">\n\t\tActive Tasks");
      out.write("</font>");
      out.write("</a>\n\t");
      out.write("</td>\n");
      out.write("</tr>\n\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("<a href=\"/admincontrol?type=history\">");
      out.write("<font class=\"linkfont\">\n\t\tActivity Log");
      out.write("</font>");
      out.write("</a>\n\t");
      out.write("</td>\n");
      out.write("<tr>\n\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("<form action=\"/gwadmin/reset\" method=\"post\">\n\t\t");
      out.write("<input type=\"hidden\" name=\"type\" value=\"reboot\">\n\t\t");
      out.write("<input type=\"submit\" value=\"  Reboot Gateway  \">\n\t\t");
      out.write("</form>\n\t");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n\t");
      out.write("</td>\n\t");
      out.write("<td  align=\"left\">\n\t");
      out.write("<B>");
      out.write("<font face=\"verdana\" size=1 color=\"blue\">");
      out.print(msg);
      out.write("</font>");
      out.write("</B>\n\t");
      out.write("<table border=\"0\" cellpadding=2 cellspacing=2 width=\"90%\">\n\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=4>\n\t\t\t");
      out.write("<font face=\"verdana\" size=2>\n\t\t\t");
      out.write("<B>Service Settings");
      out.write("</B>\n\t\t\t");
      out.write("<br>\n\t\t\t");
      out.write("<font face=\"verdana\" size=1\" color=\"333333\">Note:  Changing any of these\n\t\t\tsettings will force all current and active users of this service to\n\t\t\treauthenticate.");
      out.write("</font>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" width=\"50\">\n\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" width=\"30\">\n\t\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("</tr>\n\t");
      out.write("<form action=\"/gwadmin/reset\" method=\"post\">\n\t");
      out.write("<input type=\"hidden\" value=\"reset\" name=\"type\">\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tReset Configuration\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<input type=\"submit\" value=\"  Reset  \">\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"3\">\n\t\t\t");
      out.write("<font face=\"verdana\" size=1>\n\t\t\tThis will reset the configuration back to factory defaults.  You\n\t\t\t");
      out.write("<B>Must");
      out.write("</B> power-cycle the device after resetting the configuration.\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("</form>\n\t");
      out.write("<form action=\"/gwadmin/changepassword\" method=\"post\">\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=5>\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Change Password");
      out.write("</B>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tCurrent Password\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"password\" size=\"10\" maxlength=\"15\" \n\t\t\t\t\tname=\"iobeam.gateway.admin.password\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tNew Password\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"password\" size=\"10\" maxlength=\"15\" \n\t\t\t\t\tname=\"iobeam.gateway.admin.password.new\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tConfirm Password\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"password\" size=\"10\" maxlength=\"15\" \n\t\t\t\t\tname=\"iobeam.gateway.admin.password.new.confirm\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=2>\n\t\t\t");
      out.write("<input type=\"submit\" value=\"  Change Password  \">\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=3>&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("</form>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Gateway Configuration");
      out.write("</B>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\n\t");
      out.write("<form action=\"/gwadmin/update\" method=\"post\">\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tVenue ID\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.venue.id"));
      out.write("\"\n\t\t\t\tsize=3 maxlength=3 name=\"iobeam.gateway.venue.id\">\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">&nbsp;Do not change this value");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tTime Zone\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<SELECT name=\"iobeam.gateway.timezone\" size=1>\n\t\t\t\t");
      out.write("<option value=\"GMT\" \n\t\t\t\t\t");
      out.print((gconfig.getProperty("iobeam.gateway.timezone").equals("GMT") ?
					"selected" : ""));
      out.write("\n\t\t\t\t>GMT");
      out.write("</option>\n\t\t\t\t");
      out.write("<option value=\"EST\" \n\t\t\t\t\t");
      out.print((gconfig.getProperty("iobeam.gateway.timezone").equals("EST") ?
					"selected" : ""));
      out.write("\n\t\t\t\t>EST");
      out.write("</option>\n\t\t\t\t");
      out.write("<option value=\"CST\" \n\t\t\t\t\t");
      out.print((gconfig.getProperty("iobeam.gateway.timezone").equals("CST") ?
					"selected" : ""));
      out.write("\n\t\t\t\t>CST");
      out.write("</option>\n\t\t\t\t");
      out.write("<option value=\"MST\" \n\t\t\t\t\t");
      out.print((gconfig.getProperty("iobeam.gateway.timezone").equals("MST") ?
					"selected" : ""));
      out.write("\n\t\t\t\t>MST");
      out.write("</option>\n\t\t\t\t");
      out.write("<option value=\"PST\" \n\t\t\t\t\t");
      out.print((gconfig.getProperty("iobeam.gateway.timezone").equals("PST") ?
					"selected" : ""));
      out.write("\n\t\t\t\t>PST");
      out.write("</option>\n\t\t\t");
      out.write("</select>\n\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>");
      out.print(localtime);
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">\n\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Splash Page");
      out.write("</B>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\"colspan=\"5\">\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">\n\t\t\t");
      out.write("<B>Splash Page URL");
      out.write("</B> is the url (starting with http:// or https:// that \n\t\t\tyou want users redirected to when they open their web browsers and use\n\t\t\tthis wireless service for the first time.\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tSplash Page URL\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.anonymous.redirect.url"));
      out.write("\"\n\t\t\tname=\"iobeam.gateway.anonymous.redirect.url\" size=50>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">\n\t\t&nbsp;\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Access Control Schedule");
      out.write("</B>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\"colspan=\"5\">\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">\n\t\t\t");
      out.write("<B>Start Access");
      out.write("</B> and ");
      out.write("<B>Stop Access");
      out.write("</B> define the schedule when\n\t\t\twireless service is available.  Setting ");
      out.write("<B>Enable Access");
      out.write("</B> to \"NO\" will\n\t\t\tdisallow wireless access regardless of the schedule.\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tStart Access\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.schedule.start"));
      out.write("\"\n\t\t\tname=\"iobeam.gateway.schedule.start\" size=10>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tStop Access\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.schedule.stop"));
      out.write("\"\n\t\t\tname=\"iobeam.gateway.schedule.stop\" size=10>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tEnable Access\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t");
 boolean allowaccess = "true".equals(gconfig.getProperty(
				"iobeam.gateway.access.enabled"));
		
      out.write("\n\t\t\t");
      out.write("<input ");
      out.print(allowaccess ? "checked" : "");
      out.write(" type=\"radio\" value=\"true\"\n\t\t\tname=\"iobeam.gateway.access.enabled\">");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>Yes");
      out.write("</B>");
      out.write("</font>&nbsp;&nbsp;\n\t\t\t");
      out.write("<input ");
      out.print(allowaccess ? "" : "checked");
      out.write(" type=\"radio\" value=\"false\"\n\t\t\tname=\"iobeam.gateway.access.enabled\">");
      out.write("<font size=1 face=\"verdana\">");
      out.write("<B>No");
      out.write("</B>");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Content Filtering");
      out.write("</B>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tEnable Content Filtering\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");

			 boolean filtering = "true".equals(gconfig.getProperty(
			 	"iobeam.gateway.filtering"));

		
      out.write("\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input ");
      out.print(filtering ? "checked" : "");
      out.write(" type=\"radio\" value=\"true\"\n\t\t\tname=\"iobeam.gateway.filtering\">");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>On");
      out.write("</B>");
      out.write("</font>&nbsp;&nbsp;\n\t\t\t");
      out.write("<input ");
      out.print(filtering ? "" : "checked");
      out.write(" type=\"radio\" value=\"false\"\n\t\t\tname=\"iobeam.gateway.filtering\">");
      out.write("<font size=1 face=\"verdana\">");
      out.write("<B>Off");
      out.write("</B>");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>WLAN Network Settings");
      out.write("</B>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tRadio Identifier (SSID)\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.radio.ssid"));
      out.write("\"\n\t\t\t\tsize=10 maxlength=15 name=\"iobeam.gateway.radio.ssid\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tRadio Channel (1-12)\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.radio.channel"));
      out.write("\"\n\t\t\t\tsize=3 maxlength=3 name=\"iobeam.gateway.radio.channel\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tRadio WEP Key\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.radio.wep.key"));
      out.write("\"\n\t\t\t\tsize=15 maxlength=20 name=\"iobeam.gateway.radio.wep.key\">\n\t\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>Leave blank for no encryption");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td>");
      out.write("</td>\n\t\t");
      out.write("<td colspan=\"4\" align=\"left\">\n\t\t");
      out.write("<font face=\"verdana\" size=1>Use a 5 digit key for 40-bit or a \n\t\t13 digit key for 104-bit encryption.");
      out.write("</font>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Address\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.address.internal.1"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.address.internal.1\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Subnet\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.subnet.internal.1"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.subnet.internal.1\">&nbsp;\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">(for example 172.16.1.0/24)");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Netmask\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.netmask.internal.1"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.netmask.internal.1\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Broadcast\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.broadcast.internal.1"));
      out.write("\"\n\t\t\tsize=\"12\" maxlength=\"15\" name=\"iobeam.gateway.broadcast.internal.1\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDHCP Lease Duration\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.1.duration"));
      out.write("\"\n\t\t\tsize=\"3\" maxlength=\"2\" name=\"iobeam.gateway.routelease.internal.1.duration\">\n\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>Hours");
      out.write("</B>");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\t\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDHCP Address Range\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.1.start"));
      out.write("\"\n\t\t\tsize=\"15\" maxlength=\"15\" name=\"iobeam.gateway.routelease.internal.1.start\">\n\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>to");
      out.write("</B>");
      out.write("</font>\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.1.stop"));
      out.write("\"\n\t\t\tsize=\"15\" maxlength=\"15\" name=\"iobeam.gateway.routelease.internal.1.stop\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\t\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>ETH 1 Network Settings");
      out.write("</B>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Address\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.address.internal.2"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.address.internal.2\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Subnet\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.subnet.internal.2"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.subnet.internal.2\">&nbsp;\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">(for example 172.16.1.0/24)");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Netmask\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.netmask.internal.2"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.netmask.internal.2\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPrivate Broadcast\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.broadcast.internal.2"));
      out.write("\"\n\t\t\tsize=\"12\" maxlength=\"15\" name=\"iobeam.gateway.broadcast.internal.2\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDHCP Address Range\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.2.start"));
      out.write("\"\n\t\t\tsize=\"15\" maxlength=\"15\" name=\"iobeam.gateway.routelease.internal.2.start\">\n\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>to");
      out.write("</B>");
      out.write("</font>\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.2.stop"));
      out.write("\"\n\t\t\tsize=\"15\" maxlength=\"15\" name=\"iobeam.gateway.routelease.internal.2.stop\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\t\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDHCP Lease Duration\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.routelease.internal.2.duration"));
      out.write("\"\n\t\t\tsize=\"3\" maxlength=\"2\" name=\"iobeam.gateway.routelease.internal.2.duration\">\n\t\t\t&nbsp;");
      out.write("<font face=\"verdana\" size=1>");
      out.write("<B>Hours");
      out.write("</B>");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\t\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDNS Servers\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.address.dns.1"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.address.dns.1\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\t\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.address.dns.2"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.address.dns.2\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\" colspan=\"5\">&nbsp;");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\t");
      out.write("<B>Public Network Settings");
      out.write("</B>\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPublic Type\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
 String type = gconfig.getProperty("iobeam.gateway.external.type"); 
      out.write("\n\n\t\t\t");
      out.write("<select name=\"iobeam.gateway.external.type\" size=1>\n\t\t\t\t");
      out.write("<option value=\"dhcp\" ");
      out.print("dhcp".equals(type) ? "selected" : "");
      out.write(">dhcp");
      out.write("</option>\n\t\t\t\t");
      out.write("<option value=\"static\" ");
      out.print("static".equals(type) ? "selected" :
				"");
      out.write(">static");
      out.write("</option>\n\t\t\t");
      out.write("</select>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"3\">\n\t\t\t");
      out.write("<font face=\"verdana\" size=\"1\">If ");
      out.write("<B>dhcp");
      out.write("</B> leave the ");
      out.write("<B>address");
      out.write("</B>,\n\t\t\t");
      out.write("<b>netmask");
      out.write("</B> and ");
      out.write("<b>broadcast");
      out.write("</B> blank.");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPublic Address\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.address.external"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.address.external\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPublic Netmask\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.netmask.external"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.netmask.external\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tPublic Broadcast Address\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.broadcast.external"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.broadcast.external\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"left\">\n\t\t\t");
      out.write("<font class=\"newsbody\">\n\t\t\tDefault Gateway Address\n\t\t\t");
      out.write("</font>\n\t\t");
      out.write("</td>\n\t\t");
      out.write("<td align=\"left\" colspan=\"4\">\n\t\t\t");
      out.write("<input type=\"text\"\n\t\t\tvalue=\"");
      out.print(gconfig.getProperty("iobeam.gateway.defaultgateway.external"));
      out.write("\"\n\t\t\tsize=\"16\" maxlength=\"16\" name=\"iobeam.gateway.defaultgateway.external\">\n\t\t");
      out.write("</td>\n\t");
      out.write("</tr>\n\n\t");
      out.write("<tr>\n\t\t");
      out.write("<td align=\"center\" colspan=\"5\">\n\t\t\t");
      out.write("<input type=\"submit\" value=\"  Set  \">\n\t\t");
      out.write("</td>\n\t");
      out.write("</form>\n\t");
      out.write("</tr>\n\t");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n\n");
      out.write("</body>\n");
      out.write("</html>\n\n\n");
    } catch (Throwable t) {
      out = _jspx_out;
      if (out != null && out.getBufferSize() != 0)
        out.clearBuffer();
      if (pageContext != null) pageContext.handlePageException(t);
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(pageContext);
    }
  }
}
