package com.iobeam.portal.model.subscription;



/**
* Describes a generator that can be used by the SubscriptionBuilder
* to generate Subscriptions.
*/
public interface SubscriptionGenerator {

	/**
	* Returns the maximum number of Subscriptions that may be
	* generated by this SubscriptionGenerator.
	*/
	public int getMaxGenerationCount();


	/**
	* Returns the current number of Subscriptions that have been
	* generated by this SubscriptionGenerator.
	*/
	public int getCurrentGenerationCount();


	/**
	* Sets the current number of Subscriptions generated
	* by this SubscriptionGenerator.
	*/
	public void setCurrentGenerationCount(int count);
}
