/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class telesync_qov_QualityOfVoiceManager */

#ifndef _Included_telesync_qov_QualityOfVoiceManager
#define _Included_telesync_qov_QualityOfVoiceManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: P56_FN */
/* Inaccessible static: PAMS_FN */
/* Inaccessible static: SMJ_FN */
/* Inaccessible static: MIRS_FN */
/* Inaccessible static: HOLD_FN */
/* Inaccessible static: TF_DISABLE_FN */
/* Inaccessible static: RAF_DISABLE_FN */
/* Inaccessible static: DAF_DISABLE_FN */
/* Inaccessible static: PSQM_FN */
/* Inaccessible static: PESQ_FN */
/* Inaccessible static: PESQ */
/* Inaccessible static: PSQM */
/* Inaccessible static: SILENCE_W_2 */
/* Inaccessible static: SILENCE_W_4 */
/* Inaccessible static: SILENCE_W_6 */
/* Inaccessible static: SILENCE_W_8 */
/* Inaccessible static: SILENCE_W_10 */
/* Inaccessible static: SILENCE_W_BITS */
/* Inaccessible static: PESQ_MODEL */
/* Inaccessible static: DUMMY_FN */
/*
 * Class:     telesync_qov_QualityOfVoiceManager
 * Method:    compare
 * Signature: (JLtelesync/qov/INPUTDATA;Ltelesync/qov/INPUTDATA;Ltelesync/qov/RESULTDATA;)J
 */
JNIEXPORT jlong JNICALL Java_telesync_qov_QualityOfVoiceManager_compare__JLtelesync_qov_INPUTDATA_2Ltelesync_qov_INPUTDATA_2Ltelesync_qov_RESULTDATA_2
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     telesync_qov_QualityOfVoiceManager
 * Method:    compare
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_telesync_qov_QualityOfVoiceManager_compare__JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     telesync_qov_QualityOfVoiceManager
 * Method:    compare
 * Signature: (JLjava/lang/String;Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_telesync_qov_QualityOfVoiceManager_compare__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
