drop table users cascade constraints;

DROP PUBLIC SYNONYM USERS;

DROP SEQUENCE USER_SEQ;

DROP PUBLIC SYNONYM USER_SEQ;

DROP TABLE USERDETAIL CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM USERDETAIL;


