DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMER;

DROP SEQUENCE CUSTOMER_SEQ;

DROP PUBLIC SYNONYM CUSTOMER_SEQ;

CREATE TABLE CUSTOMER ( 
	CUSTOMERID NUMBER NOT NULL,
	USERNAME NUMBER NOT NULL,
	PASSWORD VARCHAR(150) NOT NULL,
	PASSWORDHINTS VARCHAR(254) NULL,
	CUSTOMERTYPEID NUMBER(5,0),
	LASTLOGONDATE DATE NOT NULL,
	FIRSTLOGON CHAR(1) DEFAULT ('Y'),
	ACTIVE CHAR(1) DEFAULT ('Y'),
  CONSTRAINT PK_CUSTOMER_PK
  PRIMARY KEY ( CUSTOMERID ) 
    USING INDEX 
     TABLESPACE PORTAL PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE PORTAL NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM CUSTOMER FOR CUSTOMER;

CREATE SEQUENCE CUSTOMER_SEQ START WITH 1;

CREATE PUBLIC SYNONYM CUSTOMER_SEQ FOR CUSTOMER_SEQ;

DROP TABLE CUSTOMERDETAIL CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMERDETAIL;

CREATE TABLE CUSTOMERDETAIL ( 
     CUSTOMERID           NUMBER        NOT NULL, 
     FIRSTNAME VARCHAR2(50) NOT NULL,
     LASTNAME VARCHAR2(50) NOT NULL,
     EMAILADDRESS VARCHAR2(75),
     GENDER VARCHAR2(1),
     ADDRESS1 VARCHAR2(150),
     ADDRESS2 VARCHAR2(150),
     CITY VARCHAR2(100),
     STATE VARCHAR2(2),
     ZIPCODE VARCHAR2(10),
     HOMEPHONE VARCHAR2(25),
     WORKPHONE VARCHAR2(25),
     MEMBERSINCEDATE DATE,
		 IPADDRESS VARCHAR(25),
		 MACADDRESS VARCHAR(25),
		 VENUENAME VARCHAR(50),
		 VENUETYPEID NUMBER(5,0),
		 PARENTCUSTOMERID NUMBER,
     CONSTRAINT PK_CUSTOMERDETAIL_PK
     PRIMARY KEY ( CUSTOMERID ) 
       USING INDEX 
        TABLESPACE PORTAL PCTFREE 10
        STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
      TABLESPACE PORTAL NOLOGGING 
      PCTFREE 10
      PCTUSED 40
      INITRANS 1
      MAXTRANS 255
     STORAGE ( 
      INITIAL 40960
      NEXT 40960
      PCTINCREASE 50
      MINEXTENTS 1
      MAXEXTENTS 505
      FREELISTS 1 FREELIST GROUPS 1 )
NOCACHE;

ALTER TABLE CUSTOMERDETAIL ADD CONSTRAINT FK_CUSTOMERDETAIL_CUSTOMER_ID
	FOREIGN KEY (CUSTOMERID)
	REFERENCES CUSTOMER (CUSTOMERID);

CREATE PUBLIC SYNONYM CUSTOMERDETAIL FOR CUSTOMERDETAIL;

DROP TABLE CUSTOMERTYPE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMERTYPE;

CREATE TABLE CUSTOMERTYPE (
	CUSTOMERTYPEID NUMBER        NOT NULL, 
  CUSTOMERTYPE VARCHAR2(200) NOT NULL,
     CONSTRAINT PK_CUSTOMERTYPE_PK
     PRIMARY KEY ( CUSTOMERTYPEID ) 
       USING INDEX 
        TABLESPACE PORTAL PCTFREE 10
        STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
      TABLESPACE PORTAL NOLOGGING 
      PCTFREE 10
      PCTUSED 40
      INITRANS 1
      MAXTRANS 255
     STORAGE ( 
      INITIAL 40960
      NEXT 40960
      PCTINCREASE 50
      MINEXTENTS 1
      MAXEXTENTS 505
      FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 
  
CREATE PUBLIC SYNONYM CUSTOMERTYPE FOR CUSTOMERTYPE;

DROP TABLE USERSESSION CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM USERSESSION;

DROP PUBLIC SYNONYM USERSESSION_SEQ;

DROP SEQUENCE USERSESSION_SEQ;

CREATE TABLE USERSESSION ( 
	USERSESSIONID NUMBER        NOT NULL, 
  JSESSIONID VARCHAR2(200) NOT NULL,
	CUSTOMERID NUMBER NOT NULL,
	VENUEID NUMBER NOT NULL,
	USERIPADDRESS NUMBER NOT NULL,
	USERMACADDRESS NUMBER NOT NULL,
	CONTACTID NUMBER NOT NULL,
	TIMESTAMP DATE,
	ACTIVE CHAR(1),
     CONSTRAINT PK_USERSESSION_PK
     PRIMARY KEY ( USERSESSIONID ) 
       USING INDEX 
        TABLESPACE PORTAL PCTFREE 10
        STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
      TABLESPACE PORTAL NOLOGGING 
      PCTFREE 10
      PCTUSED 40
      INITRANS 1
      MAXTRANS 255
     STORAGE ( 
      INITIAL 40960
      NEXT 40960
      PCTINCREASE 50
      MINEXTENTS 1
      MAXEXTENTS 505
      FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 
  
CREATE PUBLIC SYNONYM USERSESSION FOR USERSESSION;

CREATE SEQUENCE USERSESSION_SEQ START WITH 1;

CREATE PUBLIC SYNONYM USERSESSION_SEQ FOR USERSESSION_SEQ;

DROP TABLE VENUETYPE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM VENUETYPE;

CREATE TABLE VENUETYPE ( 
	VENUETYPEID NUMBER        NOT NULL, 
  VENUETYPE VARCHAR2(200) NOT NULL,
     CONSTRAINT PK_VENUETYPE_PK
     PRIMARY KEY ( VENUETYPEID ) 
       USING INDEX 
        TABLESPACE PORTAL PCTFREE 10
        STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
      TABLESPACE PORTAL NOLOGGING 
      PCTFREE 10
      PCTUSED 40
      INITRANS 1
      MAXTRANS 255
     STORAGE ( 
      INITIAL 40960
      NEXT 40960
      PCTINCREASE 50
      MINEXTENTS 1
      MAXEXTENTS 505
      FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 
   
CREATE PUBLIC SYNONYM VENUETYPE FOR VENUETYPE;




