DROP TABLE CUSTOMER_CONTACT CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMER_CONTACT;

DROP SEQUENCE CUSTOMER_CONTACT_SEQ;

DROP PUBLIC SYNONYM CUSTOMER_CONTACT_SEQ;

CREATE TABLE CUSTOMER_CONTACT ( 
	CUSTOMER_CONTACTID NUMBER NOT NULL,
	NAME VARCHAR(100),
	PHONENUMBER VARCHAR(100),
	FAXNUMBER VARCHAR(100),
	EMAILADDRESS VARCHAR(100),
	ADDRESSID NUMBER,

  CONSTRAINT PK_CUSTOMER_CONTACT_ID
  PRIMARY KEY ( CUSTOMER_CONTACTID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM CUSTOMER_CONTACT FOR CONTACT;

CREATE SEQUENCE CUSTOMER_CONTACT_SEQ START WITH 1;

CREATE PUBLIC SYNONYM CUSTOMER_CONTACT_SEQ FOR CONTACT_SEQ;


