DROP TABLE PRODUCT_CATEGORY CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM PRODUCT_CATEGORY;

DROP SEQUENCE PRODUCT_CATEGORY_SEQ;

DROP PUBLIC SYNONYM PRODUCT_CATEGORY_SEQ;

CREATE TABLE PRODUCT_CATEGORY ( 
	PRODUCTCATEGORYID NUMBER NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	PARENTCATEGORYID NUMBER,
	FOREIGN KEY(PARENTCATEGORYID) REFERENCES PRODUCT_CATEGORY(PRODUCTCATEGORYID),
	ACTIVE CHAR(1) DEFAULT 'Y',
  CONSTRAINT PK_PRODUCT_CATEGORY_ID
  PRIMARY KEY ( PRODUCTCATEGORYID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM PRODUCT_CATEGORY FOR PRODUCT_CATEGORY;

CREATE SEQUENCE PRODUCT_CATEGORY_SEQ START WITH 1;

CREATE PUBLIC SYNONYM PRODUCT_CATEGORY_SEQ FOR PRODUCT_CATEGORY_SEQ;


