DROP TABLE SALES_ORDER CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM SALES_ORDER;

DROP SEQUENCE SALES_ORDER_SEQ;

DROP PUBLIC SYNONYM SALES_ORDER_SEQ;

CREATE TABLE SALES_ORDER ( 
	SALESORDERID NUMBER NOT NULL,
	SALESORDERNUMBER VARCHAR(100) NOT NULL,
	SALESORDERDATE DATE NOT NULL,
	SALESPERSONID NUMBER,
	FOREIGN KEY (SALESPERSONID) REFERENCES EMPLOYEE(EMPLOYEEID),
	CUSTOMERID NUMBER NOT NULL,
	FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	SALESORDERSTATUSID NUMBER NOT NULL,
	FOREIGN KEY (SALESORDERSTATUSID) REFERENCES SALES_ORDER_STATUS(SALESORDERSTATUSID),
	EFFECTIVEDATE DATE NOT NULL,
  CONSTRAINT PK_SALES_ORDER_ID
  PRIMARY KEY ( SALESORDERID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM SALES_ORDER FOR SALES_ORDER;

CREATE SEQUENCE SALES_ORDER_SEQ START WITH 1;

CREATE PUBLIC SYNONYM SALES_ORDER_SEQ FOR SALES_ORDER_SEQ;


