DROP TABLE GATEWAY_RULESET CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM GATEWAY_RULESET;

DROP SEQUENCE GATEWAY_RULESET_SEQ;

DROP PUBLIC SYNONYM GATEWAY_RULESET_SEQ;

CREATE TABLE GATEWAY_RULESET ( 
	RULEID NUMBER NOT NULL,
	GATEWAYID NUMBER NOT NULL,
	TABLENAME varchar(15),
	CHAINNAME varchar(50),
	TARGETNAME varchar(50),
	TARGETVALUE varchar(50),
	SOURCEADDRESS VARCHAR(50),
	SOURCEINTERFACE VARCHAR(50),
	DESTINATIONADDRESS VARCHAR(50),
	DESTINATIONINTERFACE VARCHAR(50),
	PROTOCOL VARCHAR(5),
	SOURCEPORT VARCHAR(50),
	DESTINATIONPORT VARCHAR(50),
	MATCH VARCHAR(50),
	MATCHTYPE VARCHAR(50),
	MATCHVALUE VARCHAR(50),
	MATCHPROTOCOL VARCHAR(50),
	MATCHSOURCEPORT VARCHAR(50),
	MATCHDESTINATIONPORT VARCHAR(50),
	ORDERBIT NUMBER(5),
  CONSTRAINT PK_RULE_ID
  PRIMARY KEY ( RULEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM GATEWAY_RULESET FOR GATEWAY_RULESET;

CREATE SEQUENCE GATEWAY_RULESET_SEQ START WITH 1;

CREATE PUBLIC SYNONYM GATEWAY_RULESET_SEQ FOR GATEWAY_RULESET_SEQ;


