DROP TABLE ACCOUNT_ENTRY CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM ACCOUNT_ENTRY;

DROP SEQUENCE ACCOUNT_ENTRY_SEQ;

DROP PUBLIC SYNONYM ACCOUNT_ENTRY_SEQ;

CREATE TABLE ACCOUNT_ENTRY ( 
	ACCOUNTENTRYID NUMBER NOT NULL,
	ACCOUNTID NUMBER NOT NULL,
	FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID),
	ACCOUNTENTRYTYPEID NUMBER(3) NOT NULL,
	ACCOUNTENTRYDATE DATE NOT NULL,
	AMOUNT NUMBER(12,2) NOT NULL,
	PRODUCTID NUMBER,
	SUBSCRIPTIONID NUMBER,
	PAYMENTINSTRUMENTTYPEID NUMBER,
	MEMO VARCHAR2(1000),
  CONSTRAINT PK_ACCOUNT_ENTRY_ID
  PRIMARY KEY ( ACCOUNTENTRYID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM ACCOUNT_ENTRY FOR ACCOUNT_ENTRY;

CREATE SEQUENCE ACCOUNT_ENTRY_SEQ START WITH 1;

CREATE PUBLIC SYNONYM ACCOUNT_ENTRY_SEQ FOR ACCOUNT_ENTRY_SEQ;


