DROP TABLE INVOICE_STATUS CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM INVOICE_STATUS;

DROP SEQUENCE INVOICE_STATUS_SEQ;

DROP PUBLIC SYNONYM INVOICE_STATUS_SEQ;

CREATE TABLE INVOICE_STATUS ( 
	INVOICESTATUSID NUMBER NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
  CONSTRAINT PK_INVOICE_STATUS_ID
  PRIMARY KEY ( INVOICESTATUSID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM INVOICE_STATUS FOR INVOICE_STATUS;

CREATE SEQUENCE INVOICE_STATUS_SEQ START WITH 0;

CREATE PUBLIC SYNONYM INVOICE_STATUS_SEQ FOR INVOICE_STATUS_SEQ;

insert into invoice_status values(invoice_status_seq.nextval, 'open');

insert into invoice_status values(invoice_status_seq.nextval, 'pending');

insert into invoice_status values(invoice_status_seq.nextval, 'closed');

commit;

