DROP TABLE VIDEOCONFERENCE_ROOM CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM VIDEOCONFERENCE_ROOM;

DROP SEQUENCE VIDEOCONFERENCE_ROOM_SEQ;

DROP PUBLIC SYNONYM VIDEOCONFERENCE_ROOM_SEQ;

CREATE TABLE VIDEOCONFERENCE_ROOM ( 
	ROOMID NUMBER NOT NULL,
	NAME VARCHAR(200),
	CUSTOMERID NUMBER NOT NULL,
	MAXPARTICIPANTS NUMBER(5) NOT NULL,
	PASSWORD VARCHAR(255) NULL,
	FOREIGN KEY(ROOMID) REFERENCES
	PRODUCT(PRODUCTID),
  CONSTRAINT PK_ROOM_ID
  PRIMARY KEY ( ROOMID) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM VIDEOCONFERENCE_ROOM FOR VIDEOCONFERENCE_ROOM;

CREATE SEQUENCE VIDEOCONFERENCE_ROOM_SEQ START WITH 1000;

CREATE PUBLIC SYNONYM VIDEOCONFERENCE_ROOM_SEQ FOR VIDEOCONFERENCE_ROOM_SEQ;


