DROP TABLE ZIPCODES CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM ZIPCODES;

DROP SEQUENCE ZIPCODES_SEQ;

DROP PUBLIC SYNONYM ZIPCODES_SEQ;

CREATE TABLE ZIPCODES ( 
	ZIPCODEID NUMBER NOT NULL,
	ZIPCODE VARCHAR(13),
	CITY VARCHAR(100),
	STATE CHAR(2),
	LATITUDE NUMBER(10,4),
	LONGITUDE NUMBER(10,4),
  CONSTRAINT PK_ZIPCODES_ID
  PRIMARY KEY ( ZIPCODEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM ZIPCODES FOR CONTACT;

CREATE SEQUENCE ZIPCODES_SEQ START WITH 1;

CREATE PUBLIC SYNONYM ZIPCODES_SEQ FOR CONTACT_SEQ;


