DROP TABLE VENUE_TYPE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM VENUE_TYPE;

DROP SEQUENCE VENUE_TYPE_SEQ;

DROP PUBLIC SYNONYM VENUE_TYPE_SEQ;

CREATE TABLE VENUE_TYPE ( 
	VENUETYPEID NUMBER NOT NULL,
	VENUETYPE VARCHAR(100),
  CONSTRAINT PK_VENUE_TYPE_ID
  PRIMARY KEY ( VENUETYPEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM VENUE_TYPE FOR VENUE_TYPE;

CREATE SEQUENCE VENUE_TYPE_SEQ START WITH 1;

CREATE PUBLIC SYNONYM VENUE_TYPE_SEQ FOR VENUE_TYPE_SEQ;


