DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMER;

DROP SEQUENCE CUSTOMER_SEQ;

DROP PUBLIC SYNONYM CUSTOMER_SEQ;

CREATE TABLE CUSTOMER ( 
	CUSTOMERID NUMBER NOT NULL,
	PARENTCUSTOMERID NUMBER,
	CONTACTID NUMBER NOT NULL,
	SECONDARYCONTACTID NUMBER,
	BILLINGCONTACTID NUMBER,
	PAYMENTINSTRUMENTID NUMBER,
	CHANNELCODE VARCHAR(15),
	ACTIVE CHAR(1) DEFAULT ('Y'),
	CREATEDATE DATE NULL,
	FOREIGN KEY (CONTACTID)
	REFERENCES CUSTOMER_CONTACT(CUSTOMERCONTACTID),
  CONSTRAINT PK_CUSTOMER_PK
  PRIMARY KEY ( CUSTOMERID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM CUSTOMER FOR CUSTOMER;

CREATE SEQUENCE CUSTOMER_SEQ START WITH 1;

CREATE PUBLIC SYNONYM CUSTOMER_SEQ FOR CUSTOMER_SEQ;


