DROP TABLE ACCOUNT CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM ACCOUNT;

DROP SEQUENCE ACCOUNT_SEQ;

DROP PUBLIC SYNONYM ACCOUNT_SEQ;

CREATE TABLE ACCOUNT ( 
	ACCOUNTID NUMBER NOT NULL,
	ACCOUNTNUMBER VARCHAR(50) NOT NULL,
	CUSTOMERID NUMBER NOT NULL,
	FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	BILLABLECUSTOMERID NUMBER,
	ACCOUNTSTATUSID NUMBER(2) NOT NULL,
	FOREIGN KEY(ACCOUNTSTATUSID) REFERENCES ACCOUNT_STATUS(ACCOUNTSTATUSID),
  CONSTRAINT PK_ACCOUNT_ID
  PRIMARY KEY ( ACCOUNTID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM ACCOUNT FOR ACCOUNT;

CREATE SEQUENCE ACCOUNT_SEQ START WITH 1;

CREATE PUBLIC SYNONYM ACCOUNT_SEQ FOR ACCOUNT_SEQ;


