DROP TABLE USERS CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM USERS;

DROP SEQUENCE USER_SEQ;

DROP PUBLIC SYNONYM USER_SEQ;

CREATE TABLE USERS ( 
	USERID NUMBER NOT NULL,
	CUSTOMERID NUMBER,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(20) NOT NULL,
	PASSWORDSALT NUMBER,
	PASSWORDHASH VARCHAR(200),
	FOREIGN KEY (CUSTOMERID)
	REFERENCES CUSTOMER(CUSTOMERID),
  CONSTRAINT PK_USER_ID
  PRIMARY KEY ( USERID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM USERS FOR USERS;

CREATE SEQUENCE USER_SEQ START WITH 1;

CREATE PUBLIC SYNONYM USER_SEQ FOR USER_SEQ;


