DROP TABLE GATEWAY CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM GATEWAY;

DROP SEQUENCE GATEWAY_SEQ;

DROP PUBLIC SYNONYM GATEWAY_SEQ;

CREATE TABLE GATEWAY ( 
	GATEWAYID NUMBER NOT NULL,
	VENUEID NUMBER NOT NULL,
	IPADDRESS VARCHAR(15),
	NOTIFY_PORT NUMBER,
	MACADDRESS VARCHAR(20),
	TIMESTAMP DATE,
	PRIVATEIPADDRESS VARCHAR(15),
  CONSTRAINT PK_GATEWAY_ID
  PRIMARY KEY ( GATEWAYID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM GATEWAY FOR GATEWAY;

CREATE SEQUENCE GATEWAY_SEQ START WITH 1;

CREATE PUBLIC SYNONYM GATEWAY_SEQ FOR GATEWAY_SEQ;
