DROP TABLE EMPLOYEE_TYPE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM EMPLOYEE_TYPE;

DROP SEQUENCE EMPLOYEE_TYPE_SEQ;

DROP PUBLIC SYNONYM EMPLOYEE_TYPE_SEQ;

CREATE TABLE EMPLOYEE_TYPE ( 
	EMPLOYEETYPEID NUMBER NOT NULL,
	EMPLOYEETYPE VARCHAR(100) NOT NULL,
  CONSTRAINT PK_EMPLOYEE_TYPE_ID
  PRIMARY KEY ( EMPLOYEETYPEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM EMPLOYEE_TYPE FOR EMPLOYEE_TYPE;

CREATE SEQUENCE EMPLOYEE_TYPE_SEQ START WITH 1;

CREATE PUBLIC SYNONYM EMPLOYEE_TYPE_SEQ FOR EMPLOYEE_TYPE_SEQ;


