DROP TABLE PRODUCT CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM PRODUCT;

DROP SEQUENCE PRODUCT_SEQ;

DROP PUBLIC SYNONYM PRODUCT_SEQ;

CREATE TABLE PRODUCT ( 
	PRODUCTID NUMBER NOT NULL,
	PRODUCTNUMBER VARCHAR(100) NOT NULL,
	PRODUCTCATEGORYID NUMBER NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	PRICE NUMBER(10,2) NOT NULL,
	MINIMUMQUANTITY NUMBER(10) DEFAULT 1,
	ISLEASABLE CHAR(1) DEFAULT 'N',
	ISTAXABLE CHAR(1) DEFAULT 'Y',
	ISCOMMISSIONABLE CHAR(1) DEFAULT 'Y',
	DEFAULTCCOMMISSIONRATE NUMBER(4,3),
	COSTPERBILLINGCYCLE NUMBER(10,2),
	BILLINGCYCLECOUNT NUMBER,
	ACTIVE CHAR(1) DEFAULT 'Y',
	FOREIGN KEY(PRODUCTCATEGORYID) REFERENCES
	PRODUCT_CATEGORY(PRODUCTCATEGORYID),
  CONSTRAINT PK_PRODUCT_ID
  PRIMARY KEY ( PRODUCTID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM PRODUCT FOR PRODUCT;

CREATE SEQUENCE PRODUCT_SEQ START WITH 1;

CREATE PUBLIC SYNONYM PRODUCT_SEQ FOR PRODUCT_SEQ;


