DROP TABLE USER_CONTACT CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM USER_CONTACT;

DROP SEQUENCE USER_CONTACT_SEQ;

DROP PUBLIC SYNONYM USER_CONTACT_SEQ;

CREATE TABLE USER_CONTACT ( 
	USERCONTACTID NUMBER NOT NULL,
	USERID NUMBER,
	VENUEID NUMBER NOT NULL,
	IPADDRESS VARCHAR(15),
	MACADDRESS VARCHAR(20),
	ANONYMOUS CHAR(1) DEFAULT 'N',
	TIMESTAMP DATE,
  CONSTRAINT PK_USER_CONTACT_ID
  PRIMARY KEY ( USERCONTACTID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM USER_CONTACT FOR USER_CONTACT;

CREATE SEQUENCE USER_CONTACT_SEQ START WITH 1;

CREATE PUBLIC SYNONYM USER_CONTACT_SEQ FOR USER_CONTACT_SEQ;


