DROP TABLE SALES_ORDER_ITEM CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM SALES_ORDER_ITEM;

DROP SEQUENCE SALES_ORDER_ITEM_SEQ;

DROP PUBLIC SYNONYM SALES_ORDER_ITEM_SEQ;

CREATE TABLE SALES_ORDER_ITEM ( 
	SALESORDERITEMID NUMBER NOT NULL,
	SALESORDERID NUMBER,
	FOREIGN KEY (SALESORDERID) REFERENCES SALES_ORDER(SALESORDERID),
	PRODUCTID NUMBER,
	FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
	SUBSCRIPTIONPROTOTYPEID NUMBER,
	FOREIGN KEY (SUBSCRIPTIONPROTOTYPEID) REFERENCES
	SUBSCRIPTION_PROTOTYPE(SUBSCRIPTIONPROTOTYPEID),
	AMOUNT NUMBER(10,2),
	QUANTITY NUMBER,
	MAXUSERCOUNT NUMBER,
	DURATION NUMBER,
  PRIMARY KEY ( SALESORDERITEMID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM SALES_ORDER_ITEM FOR SALES_ORDER_ITEM;

CREATE SEQUENCE SALES_ORDER_ITEM_SEQ START WITH 1;

CREATE PUBLIC SYNONYM SALES_ORDER_ITEM_SEQ FOR SALES_ORDER_ITEM_SEQ;


