DROP TABLE SUBSCRIPTION CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM SUBSCRIPTION;

DROP SEQUENCE SUBSCRIPTION_SEQ;

DROP PUBLIC SYNONYM SUBSCRIPTION_SEQ;

CREATE TABLE SUBSCRIPTION ( 
	SUBSCRIPTIONID NUMBER NOT NULL,
	ACCOUNTID NUMBER NOT NULL,
	SECURE_ID NUMBER(21),
	FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID),
	SUBSCRIPTIONTYPEID NUMBER NOT NULL,
	FOREIGN KEY(SUBSCRIPTIONTYPEID) REFERENCES SUBSCRIPTION_TYPE(SUBSCRIPTIONTYPEID),
	SUBSCRIPTIONPROTOTYPEID NUMBER NOT NULL,
	FOREIGN KEY(SUBSCRIPTIONPROTOTYPEID) REFERENCES
	SUBSCRIPTION_PROTOTYPE(SUBSCRIPTIONPROTOTYPEID),
	SUBSCRIPTIONSTATUSID NUMBER NOT NULL,
	FOREIGN KEY(SUBSCRIPTIONSTATUSID) REFERENCES SUBSCRIPTION_STATUS(SUBSCRIPTIONSTATUSID),
	PARENT_SUBSCRIPTION_ID NUMBER,
	EFFECTIVE_VENUE_ID NUMBER,
	STARTDATE DATE,
	EXPIRATIONDATE DATE,
	BILLINGCYCLE NUMBER NOT NULL,
	BILLINGCYCLECOUNT NUMBER,
	CURRENTBILLINGCYCLECOUNT NUMBER,
	COSTPERBILLINGCYCLE NUMBER(10,2),
	MAXGENERATIONCOUNT NUMBER DEFAULT 0,
	CURRENTGENERATIONCOUNT NUMBER DEFAULT 0,
	ISCOMMISSIONABLE CHAR(1) DEFAULT 'Y',
	DEFAULTCOMMISSIONRATE NUMBER(5,3),
	ALLOWANONYMOUSACCESS CHAR(1) DEFAULT 'N',
	REGISTERED CHAR(1) DEFAULT 'N',
	REQUIRES_REGISTRATION CHAR(1) DEFAULT 'N',
	CHANNELCODE VARCHAR(15),
	DESCRIPTION VARCHAR(100),
  CONSTRAINT PK_SUBSCRIPTION_ID
  PRIMARY KEY ( SUBSCRIPTIONID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM SUBSCRIPTION FOR SUBSCRIPTION;

CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 100;

CREATE PUBLIC SYNONYM SUBSCRIPTION_SEQ FOR SUBSCRIPTION_SEQ;


