DROP TABLE COUNTRY CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM COUNTRY;

DROP SEQUENCE COUNTRY_SEQ;

DROP PUBLIC SYNONYM COUNTRY_SEQ;

CREATE TABLE COUNTRY ( 
	COUNTRYID NUMBER NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL,
  CONSTRAINT PK_COUNTRY_ID
  PRIMARY KEY ( COUNTRYID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM COUNTRY FOR COUNTRY;

CREATE SEQUENCE COUNTRY_SEQ START WITH 1;

CREATE PUBLIC SYNONYM COUNTRY_SEQ FOR COUNTRY_SEQ;


