DROP TABLE PAYMENT_INSTRUMENT CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM PAYMENT_INSTRUMENT;

DROP SEQUENCE PAYMENT_INSTRUMENT_SEQ;

DROP PUBLIC SYNONYM PAYMENT_INSTRUMENT_SEQ;

CREATE TABLE PAYMENT_INSTRUMENT ( 
	PAYMENTINSTRUMENTID NUMBER NOT NULL,
	PAYMENTINSTRUMENTTYPEID NUMBER NOT NULL,
	ACCOUNTNUMBER VARCHAR(100),
	SECURITYCODE VARCHAR(20),
	EXPIRATIONDATE DATE,
	ROUTINGNUMBER VARCHAR(40),
	CHECKNUMBER VARCHAR(10),
	BANKNAME VARCHAR(100),
	ACCOUNTHOLDERNAME VARCHAR(100),
	BILLINGADDRESSID NUMBER,
	FOREIGN KEY(PAYMENTINSTRUMENTTYPEID)
	REFERENCES PAYMENT_INSTRUMENT_TYPE(PAYMENTINSTRUMENTTYPEID),
  CONSTRAINT PK_PAYMENT_INSTRUMENTID
  PRIMARY KEY ( PAYMENTINSTRUMENTID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM PAYMENT_INSTRUMENT FOR PAYMENT_INSTRUMENT;

CREATE SEQUENCE PAYMENT_INSTRUMENT_SEQ START WITH 1;

CREATE PUBLIC SYNONYM PAYMENT_INSTRUMENT_SEQ FOR PAYMENT_INSTRUMENT_SEQ;


