DROP TABLE SECURITY_GROUP CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM SECURITY_GROUP;

DROP SEQUENCE SECURITY_GROUP_SEQ;

DROP PUBLIC SYNONYM SECURITY_GROUP_SEQ;

CREATE TABLE SECURITY_GROUP ( 
	SECURITYGROUPID NUMBER NOT NULL,
	GROUPNAME VARCHAR(100),
	PARENTGROUPNAME VARCHAR(100),
  CONSTRAINT PK_SECURITY_GROUP_ID
  PRIMARY KEY ( SECURITYGROUPID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM SECURITY_GROUP FOR SECURITY_GROUP;


create sequence security_group_seq start with 1;

create public synonym security_group_seq for security_group_seq;


INSERT INTO SECURITY_GROUP VALUES(security_group_seq.nextval,'administrator',null);

INSERT INTO SECURITY_GROUP VALUES(security_group_seq.nextval, 'domain admin',null);

INSERT INTO SECURITY_GROUP VALUES(security_group_seq.nextval, 'portaluser',null);

INSERT INTO SECURITY_GROUP VALUES(security_group_seq.nextval, 'subscriber','portaluser');


