DROP TABLE INVOICE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM INVOICE;

DROP SEQUENCE INVOICE_SEQ;

DROP PUBLIC SYNONYM INVOICE_SEQ;

CREATE TABLE INVOICE ( 
	INVOICEID NUMBER NOT NULL,
	INVOICENUMBER VARCHAR(20) NOT NULL,
	ACCOUNTID NUMBER NOT NULL,
	FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID),
	AMOUNTDUE NUMBER(12,2) NOT NULL,
	INVOICEDATE DATE NOT NULL,
	INVOICESTATUSID NUMBER,
	FOREIGN KEY (INVOICESTATUSID) REFERENCES INVOICE_STATUS(INVOICESTATUSID),
  CONSTRAINT PK_INVOICE_ID
  PRIMARY KEY ( INVOICEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM INVOICE FOR INVOICE;

CREATE SEQUENCE INVOICE_SEQ START WITH 1;

CREATE PUBLIC SYNONYM INVOICE_SEQ FOR INVOICE_SEQ;


