DROP TABLE VC_ROOM_USER CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM VC_ROOM_USER;

CREATE TABLE VC_ROOM_USER ( 
	ROOMID NUMBER NOT NULL,
	USERID NUMBER NOT NULL,
	FOREIGN KEY(ROOMID) REFERENCES
	PRODUCT(PRODUCTID),
  CONSTRAINT PK_VCROOMUSERID
  PRIMARY KEY ( ROOMID,USERID)
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM VC_ROOM_USER FOR VC_ROOM_USER;



