DROP TABLE INVOICE_LINE_ITEM CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM INVOICE_LINE_ITEM;

DROP SEQUENCE INVOICE_LINE_ITEM_SEQ;

DROP PUBLIC SYNONYM INVOICE_LINE_ITEM_SEQ;

CREATE TABLE INVOICE_LINE_ITEM ( 
	INVOICELINEITEMID NUMBER NOT NULL,
	INVOICEID NUMBER NOT NULL,
	FOREIGN KEY(INVOICEID) REFERENCES INVOICE(INVOICEID),
	ACCOUNTENTRYID NUMBER NOT NULL,
	FOREIGN KEY(ACCOUNTENTRYID) REFERENCES ACCOUNT_ENTRY(ACCOUNTENTRYID),
  CONSTRAINT PK_INVOICE_LINE_ITEM_ID
  PRIMARY KEY ( INVOICELINEITEMID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM INVOICE_LINE_ITEM FOR INVOICE_LINE_ITEM;

CREATE SEQUENCE INVOICE_LINE_ITEM_SEQ START WITH 1;

CREATE PUBLIC SYNONYM INVOICE_LINE_ITEM_SEQ FOR INVOICE_LINE_ITEM_SEQ;


