DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM EMPLOYEE;

DROP SEQUENCE EMPLOYEE_SEQ;

DROP PUBLIC SYNONYM EMPLOYEE_SEQ;

CREATE TABLE EMPLOYEE ( 
	EMPLOYEEID NUMBER NOT NULL,
	EMPLOYEETYPEID NUMBER NOT NULL,
	FOREIGN KEY(EMPLOYEETYPEID) REFERENCES EMPLOYEE_TYPE(EMPLOYEETYPEID),
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	ADDRESSID NUMBER NOT NULL,
	FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ADDRESSID),
	PHONENUMBER VARCHAR(50),
	EMAILADDRESS VARCHAR(100),
  CONSTRAINT PK_EMPLOYEE_ID
  PRIMARY KEY ( EMPLOYEEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM EMPLOYEE FOR EMPLOYEE;

CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1;

CREATE PUBLIC SYNONYM EMPLOYEE_SEQ FOR EMPLOYEE_SEQ;


