DROP TABLE CUSTOMER_NOTICE CASCADE CONSTRAINTS;

DROP PUBLIC SYNONYM CUSTOMER_NOTICE;

DROP SEQUENCE CUSTOMER_NOTICE_SEQ;

DROP PUBLIC SYNONYM CUSTOMER_NOTICE_SEQ;

CREATE TABLE CUSTOMER_NOTICE ( 
	CUSTOMERNOTICEID NUMBER NOT NULL,
	NOTICE VARCHAR(4000),
	VENUEID NUMBER NOT NULL,
	ACTIVE CHAR(1) DEFAULT 'Y',
	ORDERBIT NUMBER(1) DEFAULT 0,	
  CONSTRAINT PK_CUSTOMER_NOTICE_ID
  PRIMARY KEY ( CUSTOMERNOTICEID ) 
    USING INDEX 
     TABLESPACE IOBEAM PCTFREE 10
     STORAGE ( INITIAL 40K NEXT 40K PCTINCREASE 50 ))
   TABLESPACE IOBEAM NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 40960
   NEXT 40960
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 505
   FREELISTS 1 FREELIST GROUPS 1 ) 
NOCACHE;

CREATE PUBLIC SYNONYM CUSTOMER_NOTICE FOR CUSTOMER_NOTICE;

CREATE SEQUENCE CUSTOMER_NOTICE_SEQ START WITH 1;

CREATE PUBLIC SYNONYM CUSTOMER_NOTICE_SEQ FOR CUSTOMER_NOTICE_SEQ;


