CREATE VIEW V_VENUE (
VENUEID, USERNAME, PASSWORD, PASSWORDHINTS,VENUENAME, VENUETYPEID, VENUETYPE, OPERATORNAME,
IPADDRESS, MACADDRESS, PHONENUMBER, EMAILADDRESS, ADDRESS1, ADDRESS2,
CITY, STATE, ZIPCODE, PARENTCUSTOMERID, ACTIVE) AS
SELECT CD.CUSTOMERID, C.USERNAME, C.PASSWORD, C.PASSWORDHINTS,
CD.VENUENAME, CD.VENUETYPEID,
VT.VENUETYPE, CD.FIRSTNAME || ' ' || CD.LASTNAME AS OPERATORNAME,
CD.IPADDRESS, CD.MACADDRESS, CD.WORKPHONE, CD.EMAILADDRESS, CD.ADDRESS1,
CD.ADDRESS2, CD.CITY, CD.STATE, CD.ZIPCODE, CD.PARENTCUSTOMERID, C.ACTIVE
FROM CUSTOMER C, CUSTOMERDETAIL CD, VENUETYPE VT 
WHERE C.CUSTOMERID = CD.CUSTOMERID AND CD.VENUETYPEID = VT.VENUETYPEID AND
			C.CUSTOMERTYPEID = 1

