/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QualityOfVoiceManager */

#ifndef _Included_QualityOfVoiceManager
#define _Included_QualityOfVoiceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QualityOfVoiceManager
 * Method:    compare
 * Signature: (JLtelesync/qov/QualityOfVoice$INPUTDATA;Ltelesync/qov/QualityOfVoice$INPUTDATA;Ltelesync/qov/QualityOfVoice$RESULTDATA;)J
 */
JNIEXPORT jlong JNICALL Java_QualityOfVoiceManager_compare
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
